---
- name: Fetch info about VDSM
  command: bash -c "rpm -qi vdsm | grep -oE 'Version\\s+:\\s+[0-9\\.]+' | awk '{print $3}'"
  changed_when: false
  register: vdsm_version

- name: Check if VDSM version is supported for FirewallD
  fail:
    msg: "VDSM version {{ vdsm_version.stdout }} is not supported for libvirt guests."
  when:
    - "vdsm_version.stdout | version_compare('4.20', '<')"
